### ISSUE TITLE
right point to land on page when clicked on nav bar elements

### ISSUE THREAD

**Issue by whosFritz** [whosFritz/Portfolio#5]

**Comment by MaRcR11** [comment]
could not find a good way to do this, but you can try to adjust the sections manually, like the following: 

#projects-section{
  padding-top: 1px;
}

#social-media-section{
  padding-top: 10px;
}

#github-section{
  padding-top: 75px;

}

**Comment by whosFritz** [comment]
now i want the bar to collapese when clicked on, gonna fix that myself. Thank you Marc
